project:
  type: website
  output-dir: docs

website:
  title: "Computational Musicology | Bram Ruben Schoen"
  search: false
  navbar:
    background: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "Moods"
        href: moods.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    page-layout: full